VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('24')
VERSION_HOUR = int('15')
VERSION_MINUTE = int('42')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202211241542
version_date = '2022/11/24 15:42'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
