VERSION_YEAR = 2023
VERSION_MONTH = int('04')
VERSION_DAY = int('04')
VERSION_HOUR = int('02')
VERSION_MINUTE = int('10')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202304040210
version_date = '2023/04/04 02:10'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
