VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('27')
VERSION_HOUR = int('20')
VERSION_MINUTE = int('00')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202211272000
version_date = '2022/11/27 20:00'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
